version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: DEBUG
  file:
    class: logging.FileHandler
    filename: 'app.log'
    formatter: simple
    level: DEBUG
loggers:
  my_logger:
    handlers: [console, file]
    level: DEBUG
    propagate: False
root:
  handlers: [console, file]
  level: DEBUG