version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: DEBUG
  file:
    class: logging.FileHandler
    filename: 'app.log'
    formatter: simple
    level: DEBUG
loggers:
  '':  # Root logger
    handlers: [console, file]
    level: DEBUG
    propagate: False
  PIL.PngImagePlugin:  # Add this section to control PIL logs
    level: ERROR  # This will suppress DEBUG, INFO, and WARNING messages

log_settings:
  enable_logs: True