# configs/train_config.yaml

cache_dir: "/mnt/g/Mi unidad/[01] ML/stable_diffusion_kanji_generator/src/model/cache/"  # Ruta real con espacios y caracteres especiales

model:
  pretrained_model_name_or_path: "models--stabilityai--stable-diffusion-2-1-base"  # Modelo principal
  controlnet_pretrained: "models--runwayml--stable-diffusion-v1-5"  # Modelo ControlNet
  text_encoder_pretrained: "openai/clip-vit-large-patch14"
  tokenizer_pretrained: "openai/clip-vit-large-patch14"
  vae_pretrained: "stabilityai/sd-vae-ft-mse"

training:
  batch_size: 8
  learning_rate: 5e-5
  scheduler_type: "linear"
  warmup_steps: 500
  total_steps: 10000
  checkpoint_interval: 1000
  output_dir: "checkpoints/"
  noise_scheduler_config: "scheduler_config.json"  # Asegúrate de que este archivo exista y sea correcto

data:
  image_size: 512
  dataset_path: "data/dataset/dataset128.json"
  num_workers: 4